import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import "./globals.css";

const montserrat= Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "KŌRARU",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={montserrat.className}>
        <Header/>
        {children}
        <Footer/>

        </body>
    </html>
  );
}
